name: 'example'
on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Compare'
        uses: ./
        with:
          base: example_base
          compare: example_compare
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Result'
        run: echo Result is $COMPARE_RESULT_SAME
      - name: 'Foo (executed if branch are at same commit)'
        run: echo Branch are at same commit!!!
        if: env.COMPARE_RESULT_SAME
      - name: 'Bar (executed if branch are at diff commit)'
        run: echo Branch are not at same commit.
        if: env.COMPARE_RESULT_SAME
